### ISSUE TITLE
support multiple scripts & stylesheets

### ISSUE THREAD

**Issue by ungoldman** [sethvincent/create-html#12]
Hi @sethvincent! 👋 

I'm looking into using bankai for a project and see that it's using `create-html` under the hood. Yay!

However I have a small request: it seems you can only specify a single script and stylesheet, and I find myself very often needing to use more than one of each of those (from CDNs, demos, etc). Would it not be too much of a stretch to support an array of scripts or stylesheets?

Thanks!

**Comment by emcniece** [comment]
PR submitted: https://github.com/sethvincent/create-html/pull/14

**Comment by ungoldman** [comment]
Thanks @emcniece for doing the work! Thanks @sethvincent for maintaining!
