### ISSUE TITLE
CLI output to stdout by default

### ISSUE THREAD

**Issue by rreusser** [sethvincent/create-html#7]
Is it reasonable at all that the CLI could output to stdout by default? Writing to file `index.html` is currently the default. Unless I'm not aware of the solution (very possible), it's easy to send stdout to a file, but it doesn't play as nicely with piping to send to a file, read back in, then clean up the tmp file at the end. Changing it would require a major version upgrade.

**Comment by sethvincent** [comment]
I'm kinda surprised I didn't originally make it output to stdout to begin with 🙃.

Yeah, this would be reasonable. Would be cool to add a `--output index.html` option at the same time.

**Comment by rreusser** [comment]
Haha if I had $0.10 for every time I regretted an API decision. 😭 (and another $0.10 for every time I regretted the subsequent fix.) Need to get back to work at the moment, but I can try to submit a PR for that.

**Comment by sethvincent** [comment]
closed by #8
